import ../statistics/distributions

when isMainModule:
  let pm = PointMass(a: 1.2)
  let du = DiscreteUniform(k: 10)
  let be = Bernoulli(p: 0.7)
  let bi = Binomial(n: 10, p: 0.35)
  let ge = Geometric(p: 0.01)
  let po = Poisson(lambda: 4.0)

  let un = Uniform(a: 0.0, b: 5.0)
  let no = Normal(mean: 0.0, variance: 1.0)

  echo "PointMass(a: 1.2)"
  echo "pmf(0.9) = ", pm.pmf(0.9)
  echo "pmf(1.2) = ", pm.pmf(1.2)
  echo "pmf(3.0) = ", pm.pmf(3.0)
  echo "cdf(0.9) = ", pm.cdf(0.9)
  echo "cdf(1.2) = ", pm.cdf(1.2)
  echo "cdf(3.0) = ", pm.cdf(3.0)
  echo()

  echo "DiscreteUniform(k: 10)"
  echo "pmf(-5) = ", du.pmf(-5)
  echo "pmf( 2) = ", du.pmf(2)
  echo "pmf(10) = ", du.pmf(10)
  echo "pmf(40) = ", du.pmf(40)
  echo "cdf(-5) = ", du.cdf(-5)
  echo "cdf( 2) = ", du.cdf(2)
  echo "cdf(10) = ", du.cdf(10)
  echo "cdf(40) = ", du.cdf(40)
  echo()

  echo "Bernoulli(p: 0.7)"
  echo "pmf(-1) = ", be.pmf(-1)
  echo "pmf( 0) = ", be.pmf(0)
  echo "pmf( 1) = ", be.pmf(1)
  echo "pmf( 3) = ", be.pmf(3)
  echo "cdf(-1) = ", be.cdf(-1)
  echo "cdf( 0) = ", be.cdf(0)
  echo "cdf( 1) = ", be.cdf(1)
  echo "cdf( 3) = ", be.cdf(3)
  echo()

  echo "Binomial(n: 10, p: 0.35)"
  echo "pmf(-1) = ", bi.pmf(-1)
  echo "pmf( 0) = ", bi.pmf(0)
  echo "pmf( 1) = ", bi.pmf(1)
  echo "pmf( 3) = ", bi.pmf(3)
  echo "pmf( 6) = ", bi.pmf(6)
  echo "pmf(20) = ", bi.pmf(20)
  echo "cdf(-1) = ", bi.cdf(-1)
  echo "cdf( 0) = ", bi.cdf(0)
  echo "cdf( 1) = ", bi.cdf(1)
  echo "cdf( 3) = ", bi.cdf(3)
  echo "cdf( 6) = ", bi.cdf(6)
  echo "cdf(20) = ", bi.cdf(20)
  echo()

  echo "Geometric(p: 0.01)"
  echo " pmf(-1) = ", ge.pmf(-1)
  echo " pmf( 0) = ", ge.pmf(0)
  echo " pmf(10) = ", ge.pmf(10)
  echo " pmf(50) = ", ge.pmf(50)
  echo "pmf(100) = ", ge.pmf(100)
  echo "pmf(300) = ", ge.pmf(300)
  echo " cdf(-1) = ", ge.cdf(-1)
  echo " cdf( 0) = ", ge.cdf(0)
  echo " cdf(10) = ", ge.cdf(10)
  echo " cdf(50) = ", ge.cdf(50)
  echo "cdf(100) = ", ge.cdf(100)
  echo "cdf(300) = ", ge.cdf(300)
  echo()

  echo "Poisson(lambda: 4.0)"
  echo "pmf(-1) = ", po.pmf(-1)
  echo "pmf( 0) = ", po.pmf(0)
  echo "pmf( 1) = ", po.pmf(1)
  echo "pmf( 4) = ", po.pmf(4)
  echo "pmf(10) = ", po.pmf(10)
  echo "cdf(-1) = ", po.cdf(-1)
  echo "cdf( 0) = ", po.cdf(0)
  echo "cdf( 1) = ", po.cdf(1)
  echo "cdf( 4) = ", po.cdf(4)
  echo "cdf(10) = ", po.cdf(10)
  echo()

  echo "Uniform(a: 0.0, b: 5.0)"
  echo "pmf(-1.0) = ", un.pmf(-1.0)
  echo "pmf( 0.0) = ", un.pmf(0.0)
  echo "pmf( 1.0) = ", un.pmf(1.0)
  echo "pmf( 5.0) = ", un.pmf(5.0)
  echo "pmf( 6.0) = ", un.pmf(6.0)
  echo "cdf(-1.0) = ", un.cdf(-1.0)
  echo "cdf( 0.0) = ", un.cdf(0.0)
  echo "cdf( 1.0) = ", un.cdf(1.0)
  echo "cdf( 5.0) = ", un.cdf(5.0)
  echo "cdf( 6.0) = ", un.cdf(6.0)
  echo()

  echo "Normal(mean: 0.0, variance: 1.0)"
  echo "pmf(-3.4) = ", no.pmf(-3.4)
  echo "pmf(-1.1) = ", no.pmf(-1.1)
  echo "pmf( 0.0) = ", no.pmf(0.0)
  echo "pmf( 1.1) = ", no.pmf(1.1)
  echo "pmf( 3.4) = ", no.pmf(3.4)
  echo "cdf(-3.4) = ", no.cdf(-3.4)
  echo "cdf(-1.1) = ", no.cdf(-1.1)
  echo "cdf( 0.0) = ", no.cdf(0.0)
  echo "cdf( 1.1) = ", no.cdf(1.1)
  echo "cdf( 3.4) = ", no.cdf(3.4)
  echo()
